# Generated by Django 4.1.1 on 2022-10-21 19:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('periodicity_type', models.CharField(blank=True, choices=[('AN', 'ANUAL'), ('MEN', 'MENSUAL')], default='AN', max_length=50)),
                ('periodicity_value', models.IntegerField(blank=True)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('payment_period', models.CharField(choices=[('BAJA', 'BAJA')], default='BAJA', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
