# Generated by Django 3.2 on 2022-10-27 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('amount', models.CharField(blank=True, max_length=11)),
                ('periodicity_type', models.CharField(blank=True, choices=[('AN', 'ANUAL'), ('MEN', 'MENSUAL')], default='MEN', max_length=50)),
                ('periodicity_value', models.IntegerField(blank=True)),
                ('next_pay_date', models.DateTimeField(auto_now_add=True)),
                ('payment_period', models.CharField(choices=[('BAJA', 'BAJA')], default='BAJA', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('is_pay', models.BooleanField(default=False)),
                ('is_postpone', models.BooleanField(default=False)),
                ('platforms', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platforms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
