# Generated by Django 4.1.1 on 2022-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_initial_date_contract_next_pay_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='periodicity_type',
            field=models.CharField(blank=True, choices=[('AN', 'ANUAL'), ('MEN', 'MENSUAL')], default='MEN', max_length=50),
        ),
    ]
