# Generated by Django 3.2 on 2022-10-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contract_periodicity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='amount',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
