# Generated by Django 3.2 on 2022-10-26 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0004_contract_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='platforms',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platforms'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.useraccount'),
        ),
    ]
